import { pgTable, uuid, varchar, text, boolean, index, uniqueIndex, timestamp, date, jsonb } from "drizzle-orm/pg-core";
import { organizations, branches, users } from "./core";
import { patients, insuranceProviders, patientInsurances } from "./clinical";
import { visits } from "./appointment";
import { invoices } from "./billing";

export const bpjsSettings = pgTable(
  "bpjs_settings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id),
    enabled: boolean("enabled").notNull().default(false),
    mockMode: boolean("mock_mode").notNull().default(true),
    serviceBaseUrl: varchar("service_base_url", { length: 512 }),
    consId: varchar("cons_id", { length: 64 }),
    secretKey: varchar("secret_key", { length: 255 }),
    userKey: varchar("user_key", { length: 128 }),
    faskesCode: varchar("faskes_code", { length: 32 }),
    faskesName: varchar("faskes_name", { length: 255 }),
    lastTestedAt: timestamp("last_tested_at", { withTimezone: true }),
    lastTestStatus: varchar("last_test_status", { length: 255 }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("bpjs_settings_org_idx").on(t.organizationId)],
);

export const bpjsEligibilityChecks = pgTable(
  "bpjs_eligibility_checks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id),
    branchId: uuid("branch_id").references(() => branches.id),
    userId: uuid("user_id").references(() => users.id),
    checkType: varchar("check_type", { length: 32 }).notNull(),
    lookupValue: varchar("lookup_value", { length: 255 }).notNull(),
    birthDate: date("birth_date"),
    status: varchar("status", { length: 32 }).notNull().default("SUCCESS"),
    noKartu: varchar("no_kartu", { length: 32 }),
    nik: varchar("nik", { length: 32 }),
    nama: varchar("nama", { length: 255 }),
    tglLahir: date("tgl_lahir"),
    jnsPeserta: varchar("jns_peserta", { length: 255 }),
    hakKelas: varchar("hak_kelas", { length: 32 }),
    penjamin: varchar("penjamin", { length: 255 }),
    noMR: varchar("no_mr", { length: 32 }),
    statusPeserta: varchar("status_peserta", { length: 255 }),
    responseJson: jsonb("response_json"),
    errorMessage: text("error_message"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("bpjs_eligibility_checks_org_idx").on(t.organizationId, t.createdAt),
    index("bpjs_eligibility_checks_nokartu_idx").on(t.noKartu),
    index("bpjs_eligibility_checks_nik_idx").on(t.nik),
  ],
);

export const bpjsSep = pgTable(
  "bpjs_sep",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id),
    branchId: uuid("branch_id").references(() => branches.id),
    visitId: uuid("visit_id").references(() => visits.id),
    patientInsuranceId: uuid("patient_insurance_id").references(() => patientInsurances.id),
    insuranceProviderId: uuid("insurance_provider_id").references(() => insuranceProviders.id),
    noSep: varchar("no_sep", { length: 32 }),
    noKartu: varchar("no_kartu", { length: 32 }).notNull(),
    nik: varchar("nik", { length: 32 }),
    nama: varchar("nama", { length: 255 }).notNull(),
    tglLahir: date("tgl_lahir"),
    gender: varchar("gender", { length: 8 }),
    tglSep: date("tgl_sep").notNull(),
    jnsPelayanan: varchar("jns_pelayanan", { length: 32 }).notNull().default("1"),
    asalRujukan: varchar("asal_rujukan", { length: 32 }).notNull().default("4"),
    noRujukan: varchar("no_rujukan", { length: 64 }),
    tglRujukan: date("tgl_rujukan"),
    ppkRujukan: varchar("ppk_rujukan", { length: 64 }),
    poliTujuan: varchar("poli_tujuan", { length: 64 }),
    poliEksekutif: varchar("poli_eksekutif", { length: 64 }).notNull().default("0"),
    klasRawatHak: varchar("klas_rawat_hak", { length: 16 }),
    klasRawatNaik: varchar("klas_rawat_naik", { length: 16 }),
    pembiayaan: varchar("pembiayaan", { length: 16 }),
    penanggungPembiayaan: varchar("penanggung_pembiayaan", { length: 16 }),
    noMR: varchar("no_mr", { length: 32 }),
    diagnosa: varchar("diagnosa", { length: 32 }),
    cob: varchar("cob", { length: 16 }).notNull().default("0"),
    katarak: varchar("katarak", { length: 16 }).notNull().default("0"),
    lakaLantas: varchar("laka_lantas", { length: 16 }).notNull().default("0"),
    cpCob: varchar("cp_cob", { length: 16 }),
    tujuanKunj: varchar("tujuan_kunj", { length: 16 }).notNull().default("0"),
    user: varchar("user", { length: 64 }),
    catatan: text("catatan"),
    statusSubmit: varchar("status_submit", { length: 32 }).notNull().default("INSERTED"),
    metaJson: jsonb("meta_json"),
    status: varchar("status", { length: 32 }).notNull().default("ACTIVE"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("bpjs_sep_org_nokartu_nosep_idx").on(t.organizationId, t.noKartu, t.noSep),
    index("bpjs_sep_org_created_idx").on(t.organizationId, t.createdAt),
    index("bpjs_sep_visit_idx").on(t.visitId),
    index("bpjs_sep_status_idx").on(t.status),
  ],
);

export const bpjsReferrals = pgTable(
  "bpjs_referrals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id),
    branchId: uuid("branch_id").references(() => branches.id),
    patientId: uuid("patient_id").references(() => patients.id),
    noRujukan: varchar("no_rujukan", { length: 64 }).notNull(),
    jenisRujukan: varchar("jenis_rujukan", { length: 16 }),
    jenisPelayanan: varchar("jenis_pelayanan", { length: 16 }),
    tglKunjungan: date("tgl_kunjungan"),
    tglRujukan: date("tgl_rujukan"),
    tglAkhirRujukan: date("tgl_akhir_rujukan"),
    noKartu: varchar("no_kartu", { length: 32 }),
    nik: varchar("nik", { length: 32 }),
    namaPeserta: varchar("nama_peserta", { length: 255 }),
    asalFaskesKode: varchar("asal_faskes_kode", { length: 32 }),
    asalFaskesNama: varchar("asal_faskes_nama", { length: 255 }),
    poliRujukanKode: varchar("poli_rujukan_kode", { length: 32 }),
    poliRujukanNama: varchar("poli_rujukan_nama", { length: 255 }),
    diagnosaKode: varchar("diagnosa_kode", { length: 32 }),
    diagnosaNama: varchar("diagnosa_nama", { length: 255 }),
    catatan: text("catatan"),
    status: varchar("status", { length: 32 }).notNull().default("ACTIVE"),
    source: varchar("source", { length: 32 }).notNull().default("VCLAIM"),
    responseJson: jsonb("response_json"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("bpjs_referrals_org_no_idx").on(t.organizationId, t.noRujukan),
    index("bpjs_referrals_org_created_idx").on(t.organizationId, t.createdAt),
    index("bpjs_referrals_nokartu_idx").on(t.noKartu),
    index("bpjs_referrals_status_idx").on(t.status),
  ],
);

export const bpjsClaims = pgTable(
  "bpjs_claims",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id").notNull().references(() => organizations.id),
    branchId: uuid("branch_id").references(() => branches.id),
    visitId: uuid("visit_id").references(() => visits.id),
    invoiceId: uuid("invoice_id").references(() => invoices.id),
    sepId: uuid("sep_id").references(() => bpjsSep.id),
    claimNumber: varchar("claim_number", { length: 64 }).notNull(),
    noSep: varchar("no_sep", { length: 32 }),
    noKartu: varchar("no_kartu", { length: 32 }),
    namaPeserta: varchar("nama_peserta", { length: 255 }),
    tglPelayanan: date("tgl_pelayanan"),
    tglPulang: date("tgl_pulang"),
    jenisPelayanan: varchar("jenis_pelayanan", { length: 32 }).notNull().default("RAWAT_JALAN"),
    diagnosa: varchar("diagnosa", { length: 32 }),
    detailDiagnosa: varchar("detail_diagnosa", { length: 64 }),
    jumlahBebanBiaya: varchar("jumlah_beban_biaya", { length: 32 }).notNull().default("0"),
    jumlahTagihan: varchar("jumlah_tagihan", { length: 32 }).notNull().default("0"),
    totalBy40: varchar("total_by_40", { length: 32 }).notNull().default("0"),
    totalBySouth: varchar("total_by_south", { length: 32 }).notNull().default("0"),
    ttlByGroup: varchar("ttl_by_group", { length: 32 }).notNull().default("0"),
    groupByJson: jsonb("group_by_json"),
    responseJson: jsonb("response_json"),
    status: varchar("status", { length: 32 }).notNull().default("DRAFT"),
    notes: text("notes"),
    submittedBy: uuid("submitted_by").references(() => users.id),
    submittedAt: timestamp("submitted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("bpjs_claims_org_number_idx").on(t.organizationId, t.claimNumber),
    index("bpjs_claims_org_created_idx").on(t.organizationId, t.createdAt),
    index("bpjs_claims_visit_idx").on(t.visitId),
    index("bpjs_claims_status_idx").on(t.status),
  ],
);