export const PERMISSIONS = [
  "patients.view",
  "patients.create",
  "patients.update",
  "patients.delete",
  "appointments.view",
  "appointments.create",
  "appointments.update",
  "appointments.cancel",
  "appointments.delete",
  "queue.view",
  "queue.create",
  "queue.call",
  "queue.skip",
  "queue.complete",
  "medical_records.view",
  "medical_records.create",
  "medical_records.update",
  "medical_records.finalize",
  "medical_records.amend",
  "diagnoses.view",
  "diagnoses.create",
  "diagnoses.update",
  "prescriptions.view",
  "prescriptions.create",
  "prescriptions.update",
  "prescriptions.dispense",
  "pharmacy.view",
  "pharmacy.dispense",
  "inventory.view",
  "inventory.create",
  "inventory.adjust",
  "inventory.opname",
  "purchases.view",
  "purchases.create",
  "purchases.receive",
  "laboratory.view",
  "laboratory.create",
  "laboratory.process",
  "laboratory.verify",
  "radiology.view",
  "radiology.create",
  "radiology.process",
  "radiology.verify",
  "billing.view",
  "billing.create",
  "billing.update",
  "billing.void",
  "payments.view",
  "payments.create",
  "payments.refund",
  "reports.view",
  "reports.export",
  "users.view",
  "users.create",
  "users.update",
  "users.delete",
  "roles.view",
  "roles.manage",
  "settings.view",
  "settings.manage",
  "audit_logs.view",
  "bpjs.view",
  "bpjs.check",
  "bpjs.manage_sep",
  "bpjs.cancel_sep",
  "bpjs.view_referrals",
  "bpjs.manage_referrals",
  "bpjs.create_claim",
  "bpjs.submit_claim",
  "bpjs.manage_settings",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const MODULE_GROUPS: Record<string, readonly string[]> = {
  "Pasien": ["patients.view", "patients.create", "patients.update", "patients.delete"],
  "Appointment": ["appointments.view", "appointments.create", "appointments.update", "appointments.cancel", "appointments.delete"],
  "Antrian": ["queue.view", "queue.create", "queue.call", "queue.skip", "queue.complete"],
  "Rekam Medis": ["medical_records.view", "medical_records.create", "medical_records.update", "medical_records.finalize", "medical_records.amend"],
  "Diagnosis": ["diagnoses.view", "diagnoses.create", "diagnoses.update"],
  "Resep": ["prescriptions.view", "prescriptions.create", "prescriptions.update", "prescriptions.dispense"],
  "Farmasi": ["pharmacy.view", "pharmacy.dispense"],
  "Inventori": ["inventory.view", "inventory.create", "inventory.adjust", "inventory.opname"],
  "Pembelian": ["purchases.view", "purchases.create", "purchases.receive"],
  "Laboratorium": ["laboratory.view", "laboratory.create", "laboratory.process", "laboratory.verify"],
  "Radiologi": ["radiology.view", "radiology.create", "radiology.process", "radiology.verify"],
  "Billing": ["billing.view", "billing.create", "billing.update", "billing.void"],
  "Pembayaran": ["payments.view", "payments.create", "payments.refund"],
  "Laporan": ["reports.view", "reports.export"],
  "Pengguna": ["users.view", "users.create", "users.update", "users.delete"],
  "Peran": ["roles.view", "roles.manage"],
  "Pengaturan": ["settings.view", "settings.manage"],
  "Audit": ["audit_logs.view"],
  "BPJS Kesehatan": ["bpjs.view", "bpjs.check", "bpjs.manage_sep", "bpjs.cancel_sep", "bpjs.view_referrals", "bpjs.manage_referrals", "bpjs.create_claim", "bpjs.submit_claim", "bpjs.manage_settings"],
};

export const ROLE_DEFINITIONS: Record<string, { name: string; description: string; permissions: readonly string[] }> = {
  SUPER_ADMIN: {
    name: "Super Admin",
    description: "Akses penuh ke semua data dan konfigurasi sistem.",
    permissions: PERMISSIONS,
  },
  OWNER: {
    name: "Pemilik Klinik",
    description: "Akses penuh pada lingkup organisasi.",
    permissions: PERMISSIONS,
  },
  ADMIN_KLINIK: {
    name: "Admin Klinik",
    description: "Mengelola operasional sehari-hari klinik.",
    permissions: [
      "patients.view", "patients.create", "patients.update", "patients.delete",
      "appointments.view", "appointments.create", "appointments.update", "appointments.cancel", "appointments.delete",
      "queue.view", "queue.create", "queue.call", "queue.skip", "queue.complete",
      "medical_records.view", "medical_records.create", "medical_records.update", "medical_records.finalize",
      "diagnoses.view", "diagnoses.create", "diagnoses.update",
      "prescriptions.view", "prescriptions.create", "prescriptions.update", "prescriptions.dispense",
      "pharmacy.view", "pharmacy.dispense",
      "inventory.view", "inventory.create", "inventory.adjust", "inventory.opname",
      "purchases.view", "purchases.create", "purchases.receive",
      "laboratory.view", "laboratory.create", "laboratory.process", "laboratory.verify",
      "radiology.view", "radiology.create", "radiology.process", "radiology.verify",
      "billing.view", "billing.create", "billing.update", "billing.void",
      "payments.view", "payments.create", "payments.refund",
      "reports.view", "reports.export",
      "users.view", "users.create", "users.update",
      "roles.view",
      "settings.view", "settings.manage",
      "audit_logs.view",
      "bpjs.view", "bpjs.check", "bpjs.manage_sep", "bpjs.cancel_sep", "bpjs.view_referrals", "bpjs.manage_referrals", "bpjs.create_claim", "bpjs.submit_claim", "bpjs.manage_settings",
    ],
  },
  DOKTER: {
    name: "Dokter",
    description: "Melakukan pemeriksaan, rekam medis, dan resep.",
    permissions: [
      "patients.view", "patients.create", "patients.update",
      "appointments.view", "appointments.create", "appointments.update",
      "queue.view", "queue.call",
      "medical_records.view", "medical_records.create", "medical_records.update", "medical_records.finalize", "medical_records.amend",
      "diagnoses.view", "diagnoses.create", "diagnoses.update",
      "prescriptions.view", "prescriptions.create", "prescriptions.update",
      "laboratory.view", "laboratory.create",
      "radiology.view", "radiology.create",
      "billing.view",
      "reports.view",
      "bpjs.view", "bpjs.check", "bpjs.view_referrals",
    ],
  },
  PERAWAT: {
    name: "Perawat",
    description: "Mendukung klinik: sign-off antrian dan tanda vital.",
    permissions: [
      "patients.view", "patients.create", "patients.update",
      "appointments.view", "appointments.create", "appointments.update", "appointments.cancel",
      "queue.view", "queue.call", "queue.skip", "queue.complete",
      "medical_records.view",
      "diagnoses.view",
      "prescriptions.view",
      "laboratory.view",
      "radiology.view",
      "reports.view",
      "bpjs.view",
    ],
  },
  RESEPSIONIS: {
    name: "Resepsionis",
    description: "Pendaftaran pasien, appointment, dan antrian.",
    permissions: [
      "patients.view", "patients.create", "patients.update",
      "appointments.view", "appointments.create", "appointments.update", "appointments.cancel",
      "queue.view", "queue.create", "queue.call", "queue.skip", "queue.complete",
      "billing.view",
      "bpjs.view", "bpjs.check", "bpjs.manage_sep", "bpjs.cancel_sep", "bpjs.view_referrals", "bpjs.manage_referrals",
    ],
  },
  APOTEKER: {
    name: "Apoteker",
    description: "Mengelola farmasi, resep, dan inventori obat.",
    permissions: [
      "patients.view",
      "prescriptions.view", "prescriptions.dispense",
      "pharmacy.view", "pharmacy.dispense",
      "inventory.view", "inventory.create", "inventory.adjust", "inventory.opname",
      "purchases.view", "purchases.create", "purchases.receive",
      "reports.view",
    ],
  },
  KASIR: {
    name: "Kasir",
    description: "Billing dan pembayaran pasien.",
    permissions: [
      "patients.view",
      "billing.view", "billing.create", "billing.update", "billing.void",
      "payments.view", "payments.create", "payments.refund",
      "reports.view",
      "bpjs.view", "bpjs.create_claim", "bpjs.submit_claim",
    ],
  },
  PETUGAS_LAB: {
    name: "Petugas Lab",
    description: "Memproses dan memverifikasi pemeriksaan laboratorium.",
    permissions: [
      "patients.view",
      "laboratory.view", "laboratory.create", "laboratory.process", "laboratory.verify",
      "reports.view",
    ],
  },
  PETUGAS_RADIOLOGI: {
    name: "Petugas Radiologi",
    description: "Memproses dan memverifikasi pemeriksaan radiologi.",
    permissions: [
      "patients.view",
      "radiology.view", "radiology.create", "radiology.process", "radiology.verify",
      "reports.view",
    ],
  },
  MANAJER: {
    name: "Manajer",
    description: "Mengelola laporan dan pengawasan operasional.",
    permissions: [
      "patients.view",
      "appointments.view",
      "queue.view",
      "medical_records.view",
      "prescriptions.view",
      "pharmacy.view",
      "inventory.view",
      "purchases.view",
      "laboratory.view",
      "radiology.view",
      "billing.view",
      "payments.view",
      "reports.view", "reports.export",
      "users.view",
      "roles.view",
      "audit_logs.view",
      "bpjs.view", "bpjs.check", "bpjs.view_referrals", "bpjs.create_claim", "bpjs.submit_claim",
    ],
  },
};

export const ROLE_CODES = Object.keys(ROLE_DEFINITIONS);